import UserProvider from './Provider/UserProvider'
import NavBar from './components/NvaBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Music + Social Media',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="childernContainer">
          <UserProvider>
            {children}
          </UserProvider>
        </div>
      </body>
    </html>
  )
}
